---
- name: InstallDefenderForLinux
  hosts: testserver
  become: yes
  tasks:
    - name: Create Defender configuration directories.
      file:
        path: /etc/opt/microsoft/mdatp/
        state: "directory"
        mode: 0755
        owner: root
        group: root
      tags:
        - onboarding

    - name: Copy Defender Onboarding Package
      ansible.builtin.copy:
        src: /etc/ansible/playbookfiles/MicrosoftDefenderATPOnboardingLinuxServer.py
        dest: /etc/opt/microsoft/mdatp/MicrosoftDefenderATPOnboardingLinuxServer.py

    - name: Add Microsoft rpm key.
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when: ansible_os_family == "RedHat"
      tags:
        - redhat
        - repo

    - name: Add Microsoft yum repository for MDATP
      yum_repository:
        name: packages-microsoft-prod
        description: Microsoft Defender for Endpoint
        baseurl: https://packages.microsoft.com/rhel/7/prod/
      when: ansible_os_family == "RedHat"


    - name: Install MDATP
      yum:
        name: mdatp
        state: latest
        enablerepo: packages-microsoft-prod

    - name: Install Python3 to run onboarding file
      yum:
        name: 'python3'
        state: latest

    - name: Run Onboarding file
      shell: "python3 /etc/opt/microsoft/mdatp/MicrosoftDefenderATPOnboardingLinuxServer.py"

    - name: Copy Defender Configuration file
      ansible.builtin.copy:
        src: /etc/ansible/playbookfiles/mdatp_managed.json
        dest: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json

    - name: restart mdatp
      ansible.builtin.service:
        name: mdatp
        state: restarted
        enabled: true
